# Generated by Django 4.1 on 2022-09-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemontype',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
    ]
