# Generated by Django 4.1 on 2022-09-29 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_rename_name_pokemontype_type_remove_pokemon_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='caught_by',
            field=models.ManyToManyField(related_name='caught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='pokemon',
            field=models.ManyToManyField(related_name='types', to='pokemon.pokemon'),
        ),
    ]
