# Generated by Django 4.1 on 2022-09-10 01:12

from django.db import migrations, models
import django.db.models.deletion
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='creation',
            field=models.DateTimeField(default=todo_app.models.time_meow),
        ),
        migrations.AddField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=todo_app.models.d_plus_seven),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.priority')),
            ],
        ),
    ]
