# Generated by Django 4.1 on 2022-08-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('create', models.DateTimeField(auto_now=True)),
                ('importance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labapp.priority')),
            ],
        ),
    ]
