# Generated by Django 4.1 on 2022-08-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0004_alter_todo_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
