# Generated by Django 4.1 on 2022-08-26 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0005_todo_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.ForeignKey(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], on_delete=django.db.models.deletion.CASCADE, to='labapp.priority'),
        ),
    ]
