# Generated by Django 4.1 on 2022-09-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblogpost',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
