# Generated by Django 4.1 on 2022-09-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_createblogpost_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createblogpost',
            name='user',
        ),
    ]
