# Generated by Django 4.0 on 2022-09-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
