# Generated by Django 4.1 on 2022-08-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todoitem_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=200),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
