# Generated by Django 4.1 on 2022-08-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_priority_todoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.BooleanField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')]),
        ),
    ]
