# Generated by Django 4.0 on 2022-08-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
