# Generated by Django 4.1 on 2022-10-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('hp', models.FloatField()),
                ('hpperlevel', models.FloatField()),
                ('mp', models.FloatField()),
                ('mpperlevel', models.FloatField()),
                ('movespeed', models.FloatField()),
                ('armor', models.FloatField()),
                ('armorperlevel', models.FloatField()),
                ('spellblock', models.FloatField()),
                ('spellblockperlevel', models.FloatField()),
                ('attackrange', models.FloatField()),
                ('hpregen', models.FloatField()),
                ('hpregenperlevel', models.FloatField()),
                ('mpregen', models.FloatField()),
                ('mpregenperlevel', models.FloatField()),
                ('crit', models.FloatField()),
                ('critperlevel', models.FloatField()),
                ('attackdamage', models.FloatField()),
                ('attackdamageperlevel', models.FloatField()),
                ('attackspeedperlevel', models.FloatField()),
                ('attackspeed', models.FloatField()),
            ],
        ),
    ]
