# Generated by Django 4.1 on 2022-08-31 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorten',
            old_name='url',
            new_name='webpage',
        ),
    ]
