# Generated by Django 4.1 on 2022-08-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_rename_url_shorten_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten',
            name='webpage',
            field=models.CharField(max_length=1000),
        ),
    ]
