# Generated by Django 4.1 on 2022-08-31 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_alter_shorten_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorten',
            name='shorty',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
