# Generated by Django 4.1 on 2022-09-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(default='Nothing here.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
